@startuml
'https://plantuml.com/class-diagram

/'Radiostation o-- "*" Radiosendung : aggregation'/
Radiostation o-- "*" Radiosendung
Radiostation "1" -- "1..*" Mitarbeiter
Mitarbeiter <|-- Moderator
Mitarbeiter <|-- Redakteur
Redakteur <|-- Chefredakteur
Radiosendung "*" -- "1..2" Moderator
Radiosendung "*" -- "1..*" Redakteur
Radiosendung "*" -- "1" Chefredakteur

class Radiostation {
wochentagSchema: Radiosendung[]
wochenendSchema: Radiosendung[]
}

class Radiosendung {
dauer: Double
thema: String
}

class Mitarbeiter {
vorname: String
zuname: String
personalnummer: Integer
telefondurchwahl: Integer
}

class Moderator {
}

class Redakteur {
}

class Chefredakteur {
mobiletelefonnummer: Integer
}

@enduml